### ISSUE TITLE
Error: function not found

### ISSUE THREAD

**Issue by trombitomi** [VanLoo-lab/CAMDAC#12]
Dear authors,

I encountered an error when executing the pipeline step-by-step.
Installation was done according to the manual.

First I tried to run the pipeline step-by-step on the provided `.bam` files. I got the following error:
```
Error in get_allele_counts(i = a, patient_id = patient_id, sample_id = sample_id,  : 
  could not find function "get_allele_counts"
```
(CAMDAC library was loaded.)

Then I tried to run the full pipeline, which then was executed! At least to a certain extent, until I had this error:

```
Error in ghs[[sample]] : subscript out of bounds
In addition: Warning messages:
1: In dir.create(file.path(path_patient, "Copy_number", sample_id),  :
  'results//P1/Copy_number/N' already exists
2: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(count)` instead.
ℹ The deprecated feature was likely used in the CAMDAC package.
  Please report the issue to the authors.
...
```
Regardless, the pipeline actually executed the `get_allele_counts()` function, but not if run step-by-step.

I ran out of ideas where the issue might be and I feel I overlook a banal mistake (maybe at the installation?).

Any help is appreciated !
Best,
Tamas

**Comment by NMNS93** [comment]
Hi Tamas,

Thanks for raising these!

For 1) We will some remove the step by step mode, but haven't updated the documentation. You may be able to run the step by step functions with CAMDAC:: e.g. CAMDAC:::get_allele_counts()

For 2) I can see that there aren't enough SNPs found in RRBS mode on the test BAM, possibly due to the default threshold. We are working on this at the moment, but try setting the minimum coverage to 1 to see if this works

I will close this issue once both are resolved. Let me know if you have any other questions. Please note it is even better to test on a real dataset if you have one available.

**Comment by trombitomi** [comment]
Thanks for the quick reply!

1.) CAMDAC:::get_allele_counts() does the job, thanks!

2.) Threshold coverage was already set to 1 for both normal and tumor.
