### ISSUE TITLE
Could now apply CAMDAC into WGBS bam file?

### ISSUE THREAD

**Issue by guobin8216** [VanLoo-lab/CAMDAC#4]
Hi, dear guys, @NMNS93 @elarosecadieux ,

I have read your CAMDAC user manual, and I think it a very powerful tool for DNA methylation analysis. So I am extremely excited and want to hand my data using CAMDAC as soon as possible. However, **my data are WGBS's bam file.** So you mentioned "This flag will become relevant in future CAMDAC versions compatible with WGBS data." in the CAMDAC user manual, I wonder that **now could we apply CAMDAC into WGBS bam data? If okay, how should I do to let it work well?**

**Comment by guobin8216** [comment]
Looking forward to your reply! 
Thanks
Bingo

**Comment by elarosecadieux** [comment]
Hi Bingo, 
@NMNS93 has written a WGBS adaptation. Please checkout the 'wgbs' branch.
Cheers, 
Lili

**Comment by NMNS93** [comment]
Hey Lili,

I put the branch up last week as we wanted to advertise it with on a conference poster, just in time for the first WGBS question! Thanks for responding to this.

Peter and I met yesterday and the plan is to combine the two branches, hopefully by summer.

We created a `pipeline_tumor_normal` function that serves as the WGBS wrapper, described in this vignette<https://vanloo-lab.github.io/CAMDAC/articles/deconvolution.html>. Could you take a look and let us know if you have any feedback or suggestions?

Once you’re happy then we’ll use this as the interface for both wgbs and rrbs (by wrapping your existing functions).

Two notes: Future plan is to create further pipeline_* functions for each CAMDAC use case (i.e. panels, multi-sample, etc.), and have users ‘design’ the experiment by how they pass bulk samples. And to save future issues/questions like this, I’ll update the main CAMDAC README to point users to the WGBS branch (pull request by tomorrow).

Best,

Nana


From: 郭彬 ***@***.***>
Date: Tuesday, 27 September 2022 at 22:09
To: VanLoo-lab/CAMDAC ***@***.***>
Cc: Nana Mensah ***@***.***>, Mention ***@***.***>
Subject: [VanLoo-lab/CAMDAC] Could now apply CAMDAC into WGBS bam file? (Issue #4)

External Sender: Use caution.


Hi, dear guys, @NMNS93<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNMNS93&data=05%7C01%7C%7C461484c5fbac4e4a7b2108daa0cc7fc9%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637999097426462661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FlJ11AUkiAIh4EhnOJzLaUM04z8%2Fk6DfCEZVpH4z0TQ%3D&reserved=0> @elarosecadieux<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Felarosecadieux&data=05%7C01%7C%7C461484c5fbac4e4a7b2108daa0cc7fc9%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637999097426462661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DSv1RGHMSIslmDNECzEpV3IKVEySIH%2Bfhx9iSxoJJ48%3D&reserved=0> ,

I have read your CAMDAC user manual, and I think it a very powerful tool for DNA methylation analysis. So I am extremely excited and want to hand my data using CAMDAC as soon as possible. However, my data are WGBS's bam file. So you mentioned "This flag will become relevant in future CAMDAC versions compatible with WGBS data." in the CAMDAC user manual, I wonder that now could we apply CAMDAC into WGBS bam data? If okay, how should I do to let it work well?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVanLoo-lab%2FCAMDAC%2Fissues%2F4&data=05%7C01%7C%7C461484c5fbac4e4a7b2108daa0cc7fc9%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637999097426462661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P%2F4bVjnL42rklSOJTTUBhjAHmXX9DoNUGbYi5I5vCYo%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHSMBKSRDWIRBGDJEMKVDUDWANO6XANCNFSM6AAAAAAQXFHVNQ&data=05%7C01%7C%7C461484c5fbac4e4a7b2108daa0cc7fc9%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637999097426462661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ml7GAblIEe4IhW4YQEqA0%2FqWCY8G6PpTRUzzN4vADV8%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

The Francis Crick Institute Limited is a registered charity in England and Wales no. 1140062 and a company registered in England and Wales no. 06885462, with its registered office at 1 Midland Road London NW1 1AT
